import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Script from 'next/script';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        {/* Include the external script here */}
        <Script 
          src="/node_modules/preline/dist/preline.js" 
          strategy="beforeInteractive" // or "afterInteractive" based on your needs
          onLoad={() => console.log('preline.js loaded')}
        />
      </body>
    </html>
  );
}
